#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v16
# autospec commit: b858a2a
#
Name     : R-wk
Version  : 0.9.2
Release  : 21
URL      : https://cran.r-project.org/src/contrib/wk_0.9.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/wk_0.9.2.tar.gz
Summary  : Lightweight Well-Known Geometry Parsing
Group    : Development/Tools
License  : MIT
Requires: R-wk-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
well-known binary and well-known text representation of
  geometries to and from R-native formats.
  Well-known binary is compact
  and fast to parse; well-known text is human-readable
  and is useful for writing tests. These formats are
  useful in R only if the information they contain can be
  accessed in R, for which high-performance functions
  are provided here.

%package lib
Summary: lib components for the R-wk package.
Group: Libraries

%description lib
lib components for the R-wk package.


%prep
%setup -q -n wk
pushd ..
cp -a wk buildavx2
popd
pushd ..
cp -a wk buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720653454

%install
export SOURCE_DATE_EPOCH=1720653454
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/wk/DESCRIPTION
/usr/lib64/R/library/wk/INDEX
/usr/lib64/R/library/wk/LICENSE
/usr/lib64/R/library/wk/Meta/Rd.rds
/usr/lib64/R/library/wk/Meta/data.rds
/usr/lib64/R/library/wk/Meta/features.rds
/usr/lib64/R/library/wk/Meta/hsearch.rds
/usr/lib64/R/library/wk/Meta/links.rds
/usr/lib64/R/library/wk/Meta/nsInfo.rds
/usr/lib64/R/library/wk/Meta/package.rds
/usr/lib64/R/library/wk/NAMESPACE
/usr/lib64/R/library/wk/NEWS.md
/usr/lib64/R/library/wk/R/wk
/usr/lib64/R/library/wk/R/wk.rdb
/usr/lib64/R/library/wk/R/wk.rdx
/usr/lib64/R/library/wk/data/Rdata.rdb
/usr/lib64/R/library/wk/data/Rdata.rds
/usr/lib64/R/library/wk/data/Rdata.rdx
/usr/lib64/R/library/wk/help/AnIndex
/usr/lib64/R/library/wk/help/aliases.rds
/usr/lib64/R/library/wk/help/paths.rds
/usr/lib64/R/library/wk/help/wk.rdb
/usr/lib64/R/library/wk/help/wk.rdx
/usr/lib64/R/library/wk/html/00Index.html
/usr/lib64/R/library/wk/html/R.css
/usr/lib64/R/library/wk/include/wk-v1-impl.c
/usr/lib64/R/library/wk/include/wk-v1.h
/usr/lib64/R/library/wk/include/wk/experimental/wk-v1-filter-cpp11.hpp
/usr/lib64/R/library/wk/include/wk/experimental/wk-v1-handler-cpp11.hpp
/usr/lib64/R/library/wk/include/wk/experimental/wk-v1-reader-cpp11.hpp
/usr/lib64/R/library/wk/tests/testthat.R
/usr/lib64/R/library/wk/tests/testthat/Rplots.pdf
/usr/lib64/R/library/wk/tests/testthat/test-affine.R
/usr/lib64/R/library/wk/tests/testthat/test-bbox.R
/usr/lib64/R/library/wk/tests/testthat/test-chunk.R
/usr/lib64/R/library/wk/tests/testthat/test-class-data-frame.R
/usr/lib64/R/library/wk/tests/testthat/test-count.R
/usr/lib64/R/library/wk/tests/testthat/test-crc.R
/usr/lib64/R/library/wk/tests/testthat/test-data.R
/usr/lib64/R/library/wk/tests/testthat/test-debug.R
/usr/lib64/R/library/wk/tests/testthat/test-filter.R
/usr/lib64/R/library/wk/tests/testthat/test-flatten.R
/usr/lib64/R/library/wk/tests/testthat/test-format.R
/usr/lib64/R/library/wk/tests/testthat/test-grd-extract.R
/usr/lib64/R/library/wk/tests/testthat/test-grd-handle.R
/usr/lib64/R/library/wk/tests/testthat/test-grd-plot.R
/usr/lib64/R/library/wk/tests/testthat/test-grd-snap.R
/usr/lib64/R/library/wk/tests/testthat/test-grd-subset.R
/usr/lib64/R/library/wk/tests/testthat/test-grd-tile.R
/usr/lib64/R/library/wk/tests/testthat/test-grd.R
/usr/lib64/R/library/wk/tests/testthat/test-handle-crc.R
/usr/lib64/R/library/wk/tests/testthat/test-handle-rct.R
/usr/lib64/R/library/wk/tests/testthat/test-handle-sfc.R
/usr/lib64/R/library/wk/tests/testthat/test-handle-slice.R
/usr/lib64/R/library/wk/tests/testthat/test-handle-wkb.R
/usr/lib64/R/library/wk/tests/testthat/test-handle-wkt.R
/usr/lib64/R/library/wk/tests/testthat/test-handle-xy.R
/usr/lib64/R/library/wk/tests/testthat/test-handler.R
/usr/lib64/R/library/wk/tests/testthat/test-make.R
/usr/lib64/R/library/wk/tests/testthat/test-meta.R
/usr/lib64/R/library/wk/tests/testthat/test-orient.R
/usr/lib64/R/library/wk/tests/testthat/test-pkg-readr.R
/usr/lib64/R/library/wk/tests/testthat/test-pkg-sf.R
/usr/lib64/R/library/wk/tests/testthat/test-pkg-vctrs.R
/usr/lib64/R/library/wk/tests/testthat/test-plot.R
/usr/lib64/R/library/wk/tests/testthat/test-problems.R
/usr/lib64/R/library/wk/tests/testthat/test-rct.R
/usr/lib64/R/library/wk/tests/testthat/test-set.R
/usr/lib64/R/library/wk/tests/testthat/test-sfc-writer.R
/usr/lib64/R/library/wk/tests/testthat/test-trans_explicit.R
/usr/lib64/R/library/wk/tests/testthat/test-transform.R
/usr/lib64/R/library/wk/tests/testthat/test-translate.R
/usr/lib64/R/library/wk/tests/testthat/test-utils.R
/usr/lib64/R/library/wk/tests/testthat/test-vertex-filter.R
/usr/lib64/R/library/wk/tests/testthat/test-void.R
/usr/lib64/R/library/wk/tests/testthat/test-wk-crs.R
/usr/lib64/R/library/wk/tests/testthat/test-wk-rcrd.R
/usr/lib64/R/library/wk/tests/testthat/test-wk-vctr.R
/usr/lib64/R/library/wk/tests/testthat/test-wkb-writer.R
/usr/lib64/R/library/wk/tests/testthat/test-wkb.R
/usr/lib64/R/library/wk/tests/testthat/test-wkt-writer.R
/usr/lib64/R/library/wk/tests/testthat/test-wkt.R
/usr/lib64/R/library/wk/tests/testthat/test-writer.R
/usr/lib64/R/library/wk/tests/testthat/test-xy-writer.R
/usr/lib64/R/library/wk/tests/testthat/test-xyzm.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/wk/libs/wk.so
/V4/usr/lib64/R/library/wk/libs/wk.so
/usr/lib64/R/library/wk/libs/wk.so
